version: '3.8'

services:
  wordpress:
    image: wordpress:6.4.3
    platform: linux/arm64
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "@Film40110"
    volumes:
      - ./html:/var/www/html

  db:
    image: mysql:5.7.43
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "@Film40110"
      MYSQL_ROOT_PASSWORD: film40110
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    platform: linux/arm64
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: film40110
    depends_on:
      - db

volumes:
  db_data:
